"""Milestone 3 helpers: YOLOv8 fine-tuning, evaluation, hyperparameter sweep,
detection gallery and results document.

Used by notebooks/06_yolov8_training_evaluation.ipynb and src/run_milestone3.py,
so the notebook and the one-command CLI produce identical outputs.

Outputs (all relative to the repo root):
    detection_dataset/data.yaml                  Ultralytics dataset config
    runs/milestone3/<run>/                       raw Ultralytics run folders (git-ignored)
    models/celeba_yolov8_best.pt                 final fine-tuned checkpoint
    results/milestone3/                          metrics, sweep tables, plots, logs, gallery
    docs/milestone3_detection_results.md         detection-results document
"""
from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
M2_DATASET_DIR = REPO_ROOT / "detection_dataset"        # Milestone 2 submission (30 images)
SCALED_DATASET_DIR = REPO_ROOT / "detection_dataset_m3"  # src/build_m3_scaled_dataset.py
DATASET_DIR = SCALED_DATASET_DIR                         # dataset the sweep and final model use
RUNS_DIR = REPO_ROOT / "runs" / "milestone3"
RESULTS_DIR = REPO_ROOT / "results" / "milestone3"
MODELS_DIR = REPO_ROOT / "models"
FINAL_WEIGHTS = MODELS_DIR / "celeba_yolov8_best.pt"
DOC_PATH = REPO_ROOT / "docs" / "milestone3_detection_results.md"
IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp"}

# Group 02's own identities (the rest come from the class-wide pool).
OUR_GROUP_CELEB_IDS = {"3", "7", "1212", "8335"}

# Ultralytics' default prediction thresholds.
DEFAULT_CONF = 0.25
DEFAULT_NMS_IOU = 0.7
MATCH_IOU = 0.5  # IoU needed for a prediction to count as finding a face


# --------------------------------------------------------------------------- #
# Dataset
# --------------------------------------------------------------------------- #
def load_class_names(dataset_dir: Path | None = None) -> dict[int, str]:
    """class_id -> 'celeb_<CelebA identity>' from the dataset's classes.json (same ids in M2 and M3)."""
    dataset_dir = Path(dataset_dir or DATASET_DIR)
    mapping = json.loads((dataset_dir / "classes.json").read_text(encoding="utf-8"))
    return {int(cid): f"celeb_{celeb}" for celeb, cid in sorted(mapping.items(), key=lambda kv: kv[1])}


def is_our_group(name: str) -> bool:
    return name.replace("celeb_", "") in OUR_GROUP_CELEB_IDS


def write_data_yaml(dataset_dir: Path | None = None) -> Path:
    """Write detection_dataset/data.yaml and return its absolute path.

    No `path:` key on purpose: Ultralytics then resolves train/val/test relative
    to the YAML's own folder, so the same file works on Colab, Windows and Linux
    as long as the *absolute* YAML path is passed in.
    """
    dataset_dir = Path(dataset_dir or DATASET_DIR)
    names = load_class_names(dataset_dir)
    lines = [
        "# YOLOv8 dataset config for the synthetic multi-celebrity detection dataset.",
        "# Split folders are resolved relative to this file. Generated by src/m3_detection.py.",
        "train: train/images",
        "val: val/images",
        "test: test/images",
        f"nc: {len(names)}",
        "names:",
    ]
    lines += [f"  {cid}: {name}" for cid, name in names.items()]
    path = dataset_dir / "data.yaml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path.resolve()


def list_images(split: str, dataset_dir: Path | None = None) -> list[Path]:
    folder = Path(dataset_dir or DATASET_DIR) / split / "images"
    return sorted(p for p in folder.iterdir() if p.suffix.lower() in IMG_EXTS)


def label_path_for(image_path: Path) -> Path:
    return image_path.parent.parent / "labels" / f"{image_path.stem}.txt"


def read_yolo_labels(label_path: Path, width: int, height: int) -> tuple[np.ndarray, np.ndarray]:
    """Return (class_ids[N], boxes_xyxy_pixels[N,4]) from a YOLO label file."""
    if not label_path.is_file() or not label_path.read_text().strip():
        return np.zeros(0, dtype=int), np.zeros((0, 4))
    rows = np.loadtxt(label_path, ndmin=2)
    cls = rows[:, 0].astype(int)
    xc, yc, w, h = rows[:, 1] * width, rows[:, 2] * height, rows[:, 3] * width, rows[:, 4] * height
    boxes = np.stack([xc - w / 2, yc - h / 2, xc + w / 2, yc + h / 2], axis=1)
    return cls, boxes


def split_summary(dataset_dir: Path | None = None) -> "pd.DataFrame":
    """Images, faces and identity coverage per split."""
    import pandas as pd

    dataset_dir = Path(dataset_dir or DATASET_DIR)
    names = load_class_names(dataset_dir)
    rows = []
    for split in ("train", "val", "test"):
        images = list_images(split, dataset_dir)
        classes = []
        for img in images:
            text = label_path_for(img).read_text().split()
            classes += [int(float(v)) for v in text[0::5]]
        present = sorted(set(classes))
        missing = [names[c] for c in names if c not in present]
        rows.append({
            "split": split,
            "images": len(images),
            "faces": len(classes),
            "identities_present": len(present),
            "identities_missing": ", ".join(missing) if missing else "-",
        })
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------- #
# Training
# --------------------------------------------------------------------------- #
@dataclass
class RunConfig:
    """One training configuration in the sweep."""

    name: str
    description: str
    model: str = "yolov8n.pt"  # COCO-pretrained starting checkpoint
    lr0: float = 0.001
    imgsz: int = 640
    aug: dict = field(default_factory=dict)  # Ultralytics augmentation overrides

    def as_row(self) -> dict:
        aug = ", ".join(f"{k}={v}" for k, v in self.aug.items()) or "Ultralytics defaults"
        return {"run": self.name, "model": self.model.replace(".pt", ""), "lr0": self.lr0, "imgsz": self.imgsz, "augmentation": aug,
                "what changes": self.description}


# Light augmentation: no mosaic/mixing, gentle colour and scale jitter. The
# dataset was already augmented offline in Milestone 2, so this tests whether
# YOLO's own (strong) online augmentation still helps on top of that.
LIGHT_AUG = {"mosaic": 0.0, "scale": 0.2, "translate": 0.05, "hsv_h": 0.005, "hsv_s": 0.3, "hsv_v": 0.2}

SWEEP_CONFIGS = [
    RunConfig("baseline", "Reference: AdamW lr0=0.001, 640 px, default online augmentation"),
    RunConfig("lr_low", "Learning rate 5x lower", lr0=0.0002),
    RunConfig("lr_high", "Learning rate 5x higher", lr0=0.005),
    RunConfig("imgsz_416", "Smaller input resolution (faster, smaller faces)", imgsz=416),
    RunConfig("aug_light", "Lighter online augmentation (no mosaic, gentler jitter)", aug=LIGHT_AUG),
    RunConfig("yolov8s_aug_light", "Larger model (YOLOv8s, ~3x parameters) with lighter augmentation",
              model="yolov8s.pt", aug=LIGHT_AUG),
]


def train_run(cfg: RunConfig, data_yaml: Path, *, model: str | None = None, epochs: int = 100,
              patience: int = 30, batch: int = 16, device=None, seed: int = 42) -> Path:
    """Fine-tune a pretrained YOLOv8 checkpoint with one configuration; return the run folder.

    optimizer is fixed to AdamW because Ultralytics' default optimizer="auto"
    silently ignores lr0, which would make the learning-rate sweep meaningless.
    """
    from ultralytics import YOLO

    options = dict(
        data=str(data_yaml), epochs=epochs, patience=patience, imgsz=cfg.imgsz, batch=batch,
        optimizer="AdamW", lr0=cfg.lr0, seed=seed, deterministic=True, workers=2,
        project=str(RUNS_DIR), name=cfg.name, exist_ok=True, plots=True, verbose=False,
        **cfg.aug,
    )
    if device is not None:
        options["device"] = device
    yolo = YOLO(model or cfg.model)
    yolo.train(**options)
    run_dir = Path(yolo.trainer.save_dir)
    if not (run_dir / "weights" / "best.pt").is_file():
        raise FileNotFoundError(f"Run {cfg.name} did not produce weights/best.pt in {run_dir}")
    return run_dir


def read_results_csv(run_dir: Path) -> "pd.DataFrame":
    import pandas as pd

    df = pd.read_csv(run_dir / "results.csv")
    df.columns = [c.strip() for c in df.columns]  # older Ultralytics pads column names
    return df


# --------------------------------------------------------------------------- #
# Evaluation
# --------------------------------------------------------------------------- #
def _np(x) -> np.ndarray:
    return x.cpu().numpy() if hasattr(x, "cpu") else np.asarray(x)


def ultralytics_metrics(weights: Path, data_yaml: Path, split: str, imgsz: int = 640,
                        name: str | None = None) -> dict:
    """Standard Ultralytics detection metrics (mAP@0.5, mAP@0.5:0.95, P, R) overall and per class."""
    from ultralytics import YOLO

    model = YOLO(str(weights))
    m = model.val(data=str(data_yaml), split=split, imgsz=imgsz, plots=True, verbose=False,
                  project=str(RUNS_DIR), name=name or f"val_{split}", exist_ok=True)
    box = m.box
    per_class = {}
    for i, cid in enumerate(_np(box.ap_class_index).astype(int)):
        per_class[int(cid)] = {
            "precision": float(_np(box.p)[i]), "recall": float(_np(box.r)[i]),
            "mAP50": float(_np(box.ap50)[i]), "mAP50-95": float(_np(box.ap)[i]),
        }
    return {
        "precision": float(box.mp), "recall": float(box.mr),
        "mAP50": float(box.map50), "mAP50-95": float(box.map),
        "per_class": per_class, "save_dir": str(getattr(m, "save_dir", "")),
    }


def box_iou(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Pairwise IoU between boxes a[N,4] and b[M,4] in xyxy format -> [N,M]."""
    if len(a) == 0 or len(b) == 0:
        return np.zeros((len(a), len(b)))
    x1 = np.maximum(a[:, None, 0], b[None, :, 0])
    y1 = np.maximum(a[:, None, 1], b[None, :, 1])
    x2 = np.minimum(a[:, None, 2], b[None, :, 2])
    y2 = np.minimum(a[:, None, 3], b[None, :, 3])
    inter = np.clip(x2 - x1, 0, None) * np.clip(y2 - y1, 0, None)
    area_a = (a[:, 2] - a[:, 0]) * (a[:, 3] - a[:, 1])
    area_b = (b[:, 2] - b[:, 0]) * (b[:, 3] - b[:, 1])
    return inter / (area_a[:, None] + area_b[None, :] - inter + 1e-9)


@dataclass
class ImageResult:
    image: Path
    gt_cls: np.ndarray
    gt_boxes: np.ndarray
    pr_cls: np.ndarray
    pr_boxes: np.ndarray
    pr_conf: np.ndarray
    pr_status: list  # per prediction: "correct" | "wrong_identity" | "false_positive"
    pr_gt: list      # matched ground-truth index or -1
    pr_iou: list     # IoU with matched ground truth (0 if unmatched)
    gt_status: list  # per ground truth: "correct" | "wrong_identity" | "missed"


def match_predictions(gt_cls, gt_boxes, pr_cls, pr_boxes, pr_conf, iou_thr: float = MATCH_IOU):
    """Greedy, confidence-ordered matching of predictions to ground-truth faces.

    A prediction overlapping an unclaimed face with IoU >= iou_thr claims it:
    "correct" if the identity matches (preferred when several faces overlap),
    otherwise "wrong_identity" (face found, wrong celebrity). Predictions that
    claim nothing are "false_positive"; faces never claimed are "missed".
    """
    ious = box_iou(pr_boxes, gt_boxes)
    gt_status = ["missed"] * len(gt_cls)
    pr_status, pr_gt, pr_iou = ["false_positive"] * len(pr_cls), [-1] * len(pr_cls), [0.0] * len(pr_cls)
    for p in np.argsort(-pr_conf):
        free = [g for g in range(len(gt_cls)) if gt_status[g] == "missed" and ious[p, g] >= iou_thr]
        if not free:
            continue
        same = [g for g in free if gt_cls[g] == pr_cls[p]]
        pool = same or free
        g = max(pool, key=lambda k: ious[p, k])
        status = "correct" if same else "wrong_identity"
        gt_status[g], pr_status[p], pr_gt[p], pr_iou[p] = status, status, g, float(ious[p, g])
    return pr_status, pr_gt, pr_iou, gt_status


def predict_and_match(model, images: list[Path], *, conf: float = DEFAULT_CONF,
                      nms_iou: float = DEFAULT_NMS_IOU, imgsz: int = 640) -> list[ImageResult]:
    """Run the detector on images that have YOLO labels and match predictions to ground truth."""
    results = model.predict(source=[str(p) for p in images], conf=conf, iou=nms_iou, imgsz=imgsz,
                            verbose=False)
    out = []
    for path, r in zip(images, results):
        h, w = r.orig_shape[:2]
        gt_cls, gt_boxes = read_yolo_labels(label_path_for(path), w, h)
        pr_boxes = _np(r.boxes.xyxy).reshape(-1, 4)
        pr_cls = _np(r.boxes.cls).astype(int).reshape(-1)
        pr_conf = _np(r.boxes.conf).reshape(-1)
        pr_status, pr_gt, pr_iou, gt_status = match_predictions(gt_cls, gt_boxes, pr_cls, pr_boxes, pr_conf)
        out.append(ImageResult(path, gt_cls, gt_boxes, pr_cls, pr_boxes, pr_conf,
                               pr_status, pr_gt, pr_iou, gt_status))
    return out


def summarize(results: list[ImageResult]) -> dict:
    """Precision, recall, F1 and IoU at one operating point (conf + NMS threshold)."""
    n_gt = sum(len(r.gt_cls) for r in results)
    n_pred = sum(len(r.pr_cls) for r in results)
    correct = sum(s == "correct" for r in results for s in r.pr_status)
    wrong = sum(s == "wrong_identity" for r in results for s in r.pr_status)
    fp = sum(s == "false_positive" for r in results for s in r.pr_status)
    ious = [iou for r in results for s, iou in zip(r.pr_status, r.pr_iou) if s == "correct"]
    loc_ious = [iou for r in results for s, iou in zip(r.pr_status, r.pr_iou) if s != "false_positive"]
    precision = correct / n_pred if n_pred else 0.0
    recall = correct / n_gt if n_gt else 0.0
    return {
        "faces": n_gt, "predictions": n_pred, "correct": correct, "wrong_identity": wrong,
        "false_positive": fp, "missed": n_gt - correct - wrong,
        "precision": precision, "recall": recall,
        "f1": 2 * precision * recall / (precision + recall) if precision + recall else 0.0,
        "face_localization_rate": (correct + wrong) / n_gt if n_gt else 0.0,
        "mean_iou": float(np.mean(ious)) if ious else 0.0,
        "mean_iou_all_localized": float(np.mean(loc_ious)) if loc_ious else 0.0,
    }


def per_class_iou(results: list[ImageResult], names: dict[int, str]) -> dict[int, dict]:
    stats = {cid: {"faces": 0, "correct": 0, "ious": []} for cid in names}
    for r in results:
        for g, cid in enumerate(r.gt_cls):
            stats[int(cid)]["faces"] += 1
        for s, g, iou in zip(r.pr_status, r.pr_gt, r.pr_iou):
            if s == "correct":
                cid = int(r.gt_cls[g])
                stats[cid]["correct"] += 1
                stats[cid]["ious"].append(iou)
    return {cid: {"faces": v["faces"], "correct": v["correct"],
                  "mean_iou": float(np.mean(v["ious"])) if v["ious"] else float("nan")}
            for cid, v in stats.items()}


def threshold_sweep(weights: Path, images: list[Path], *, confs=(0.05, 0.1, 0.25, 0.4, 0.5, 0.6, 0.75, 0.9),
                    nms_ious=(0.3, 0.45, 0.6, 0.7, 0.8), imgsz: int = 640) -> tuple["pd.DataFrame", "pd.DataFrame"]:
    """Inference-time sweep: confidence threshold (NMS fixed at default) and NMS IoU (conf fixed at default)."""
    import pandas as pd
    from ultralytics import YOLO

    model = YOLO(str(weights))
    conf_rows = [{"conf": c, "nms_iou": DEFAULT_NMS_IOU,
                  **summarize(predict_and_match(model, images, conf=c, nms_iou=DEFAULT_NMS_IOU, imgsz=imgsz))}
                 for c in confs]
    nms_rows = [{"conf": DEFAULT_CONF, "nms_iou": t,
                 **summarize(predict_and_match(model, images, conf=DEFAULT_CONF, nms_iou=t, imgsz=imgsz))}
                for t in nms_ious]
    return pd.DataFrame(conf_rows), pd.DataFrame(nms_rows)


# --------------------------------------------------------------------------- #
# Plots
# --------------------------------------------------------------------------- #
def plot_loss_curves(run_dir: Path, out_path: Path, title: str) -> Path:
    import matplotlib.pyplot as plt

    df = read_results_csv(run_dir)
    fig, axes = plt.subplots(1, 4, figsize=(18, 4))
    for ax, loss in zip(axes[:3], ("box_loss", "cls_loss", "dfl_loss")):
        ax.plot(df["epoch"], df[f"train/{loss}"], label="train")
        ax.plot(df["epoch"], df[f"val/{loss}"], label="validation")
        ax.set_title(loss.replace("_", " "))
        ax.set_xlabel("epoch")
        ax.legend()
    axes[3].plot(df["epoch"], df["metrics/mAP50(B)"], label="mAP@0.5")
    axes[3].plot(df["epoch"], df["metrics/mAP50-95(B)"], label="mAP@0.5:0.95")
    axes[3].set_title("validation mAP")
    axes[3].set_xlabel("epoch")
    axes[3].set_ylim(0, 1.02)
    axes[3].legend()
    fig.suptitle(title)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=120)
    plt.close(fig)
    return out_path


def plot_sweep_curves(run_dirs: dict[str, Path], out_path: Path) -> Path:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(13, 4))
    for name, run_dir in run_dirs.items():
        df = read_results_csv(run_dir)
        axes[0].plot(df["epoch"], df["val/box_loss"] + df["val/cls_loss"] + df["val/dfl_loss"], label=name)
        axes[1].plot(df["epoch"], df["metrics/mAP50-95(B)"], label=name)
    axes[0].set_yscale("log")  # a diverging run can spike by orders of magnitude
    axes[0].set_title("validation loss (box + cls + dfl), log scale")
    axes[1].set_title("validation mAP@0.5:0.95")
    axes[1].set_ylim(0, 1.02)
    for ax in axes:
        ax.set_xlabel("epoch")
        ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=120)
    plt.close(fig)
    return out_path


def plot_threshold_sweep(conf_df, nms_df, out_path: Path) -> Path:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(13, 4))
    for df, ax, key, label in ((conf_df, axes[0], "conf", "confidence threshold (NMS IoU = 0.7)"),
                               (nms_df, axes[1], "nms_iou", "NMS IoU threshold (conf = 0.25)")):
        for metric in ("precision", "recall", "f1", "mean_iou"):
            ax.plot(df[key], df[metric], marker="o", label=metric)
        ax.set_xlabel(label)
        ax.set_ylim(0, 1.02)
        ax.legend()
    fig.suptitle("Inference-threshold sweep on the test split")
    fig.tight_layout()
    fig.savefig(out_path, dpi=120)
    plt.close(fig)
    return out_path


# --------------------------------------------------------------------------- #
# Gallery
# --------------------------------------------------------------------------- #
COLORS = {"correct": (40, 170, 40), "wrong_identity": (0, 0, 220), "false_positive": (0, 140, 255),
          "missed": (200, 60, 200)}  # BGR


def draw_result(r: ImageResult, names: dict[int, str]) -> np.ndarray:
    """Predictions coloured by outcome; missed faces drawn as dashed magenta boxes."""
    import cv2

    img = cv2.imread(str(r.image))
    thick = max(2, img.shape[0] // 320)
    for g, status in enumerate(r.gt_status):
        if status == "missed":
            x1, y1, x2, y2 = r.gt_boxes[g].astype(int)
            for x in range(x1, x2, 12):
                cv2.line(img, (x, y1), (min(x + 6, x2), y1), COLORS["missed"], thick)
                cv2.line(img, (x, y2), (min(x + 6, x2), y2), COLORS["missed"], thick)
            for y in range(y1, y2, 12):
                cv2.line(img, (x1, y), (x1, min(y + 6, y2)), COLORS["missed"], thick)
                cv2.line(img, (x2, y), (x2, min(y + 6, y2)), COLORS["missed"], thick)
            cv2.putText(img, f"MISSED {names[int(r.gt_cls[g])]}", (x1 + 3, y2 - 6),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.4, COLORS["missed"], 1, cv2.LINE_AA)
    for p in range(len(r.pr_cls)):
        x1, y1, x2, y2 = r.pr_boxes[p].astype(int)
        color = COLORS[r.pr_status[p]]
        cv2.rectangle(img, (x1, y1), (x2, y2), color, thick)
        label = f"{names[int(r.pr_cls[p])]} {r.pr_conf[p]:.2f}"
        if r.pr_status[p] == "wrong_identity":
            label += f" (is {names[int(r.gt_cls[r.pr_gt[p]])]})"
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.42, 1)
        ty = max(y1, th + 4)
        # Keep the label inside the image: shift it left when it would run past the right edge.
        lx = max(0, min(x1, img.shape[1] - tw - 4))
        cv2.rectangle(img, (lx, ty - th - 4), (lx + tw + 4, ty), color, -1)
        cv2.putText(img, label, (lx + 2, ty - 3), cv2.FONT_HERSHEY_SIMPLEX, 0.42, (255, 255, 255), 1,
                    cv2.LINE_AA)
    return img


def caption_for(r: ImageResult, names: dict[int, str], context: str) -> str:
    n = len(r.gt_cls)
    correct = r.gt_status.count("correct")
    parts = [f"{context}: {correct}/{n} faces detected with the correct identity"]
    good_conf = [c for c, s in zip(r.pr_conf, r.pr_status) if s == "correct"]
    if good_conf:
        parts.append(f"confidence {min(good_conf):.2f}-{max(good_conf):.2f}")
    missed = [names[int(r.gt_cls[g])] for g, s in enumerate(r.gt_status) if s == "missed"]
    if missed:
        parts.append("missed " + ", ".join(missed))
    confusions = [f"{names[int(r.gt_cls[g])]} predicted as {names[int(r.pr_cls[p])]}"
                  for p, (s, g) in enumerate(zip(r.pr_status, r.pr_gt)) if s == "wrong_identity"]
    if confusions:
        parts.append("identity confusion: " + "; ".join(confusions))
    fps = sum(s == "false_positive" for s in r.pr_status)
    if fps:
        parts.append(f"{fps} extra box(es) on background or duplicate faces")
    return f"**{outcome_label(correct, n)}.** " + "; ".join(parts) + "."


def outcome_label(correct: int, faces: int) -> str:
    """Success: at least 8 of 9 faces right; Partial: at least half; Failure: fewer."""
    share = correct / faces if faces else 0.0
    return "Success" if share >= 8 / 9 else "Partial" if share >= 0.5 else "Failure"


def make_stress_images(images: list[Path], out_dir: Path) -> list[tuple[Path, str]]:
    """Harder, labelled variants of test images to surface instructive failures.

    small  : frame shrunk to 45% and placed on a grey canvas (smaller faces)
    dark   : exposure cut to 30% (poor lighting)
    blur   : heavy Gaussian blur (out-of-focus photo)
    crowded: two frames side by side squeezed into one 640 frame (18 small faces)
    Labels are transformed exactly, so the same matching code scores them.
    """
    import cv2

    (out_dir / "images").mkdir(parents=True, exist_ok=True)
    (out_dir / "labels").mkdir(parents=True, exist_ok=True)
    made = []

    def save(img, rows, stem, desc):
        path = out_dir / "images" / f"{stem}.jpg"
        cv2.imwrite(str(path), img)
        (out_dir / "labels" / f"{stem}.txt").write_text(
            "\n".join(f"{int(c)} {x:.6f} {y:.6f} {w:.6f} {h:.6f}" for c, x, y, w, h in rows) + "\n")
        made.append((path, desc))

    def rows_of(p):
        return np.loadtxt(label_path_for(p), ndmin=2)

    for p in images[:2]:
        img = cv2.imread(str(p))
        h, w = img.shape[:2]
        rows = rows_of(p)
        s, ox, oy = 0.45, 0.30, 0.40
        canvas = np.full_like(img, 128)
        small = cv2.resize(img, (int(w * s), int(h * s)))
        x0, y0 = int(w * ox), int(h * oy)
        canvas[y0:y0 + small.shape[0], x0:x0 + small.shape[1]] = small
        r2 = rows.copy()
        r2[:, 1] = rows[:, 1] * small.shape[1] / w + x0 / w
        r2[:, 2] = rows[:, 2] * small.shape[0] / h + y0 / h
        r2[:, 3] = rows[:, 3] * small.shape[1] / w
        r2[:, 4] = rows[:, 4] * small.shape[0] / h
        save(canvas, r2, f"{p.stem}_small", "Stress test (faces shrunk to 45%)")
        save(np.clip(img.astype(np.float32) * 0.30, 0, 255).astype(np.uint8), rows, f"{p.stem}_dark",
             "Stress test (exposure cut to 30%)")
        save(cv2.GaussianBlur(img, (0, 0), 4), rows, f"{p.stem}_blur", "Stress test (heavy blur)")
    if len(images) >= 2:
        a, b = cv2.imread(str(images[0])), cv2.imread(str(images[1]))
        h, w = a.shape[:2]
        both = cv2.resize(np.hstack([a, cv2.resize(b, (w, h))]), (w, h))
        ra, rb = rows_of(images[0]).copy(), rows_of(images[1]).copy()
        for rr, off in ((ra, 0.0), (rb, 0.5)):
            rr[:, 1] = rr[:, 1] / 2 + off
            rr[:, 3] = rr[:, 3] / 2
        save(both, np.vstack([ra, rb]), "crowded_two_frames", "Stress test (two frames squeezed together)")
    return made


def build_gallery(weights: Path, names: dict[int, str], out_dir: Path, dataset_dir: Path | None = None,
                  conf: float = DEFAULT_CONF, nms_iou: float = DEFAULT_NMS_IOU, imgsz: int = 640) -> "pd.DataFrame":
    """Annotated predictions for every test image plus stress variants, with captions."""
    import cv2
    import pandas as pd
    from ultralytics import YOLO

    dataset_dir = Path(dataset_dir or DATASET_DIR)
    model = YOLO(str(weights))
    out_dir.mkdir(parents=True, exist_ok=True)
    groups = [(list_images("test", dataset_dir), "Test split")]
    stress = make_stress_images(list_images("test", dataset_dir), out_dir.parent / "stress_test")
    rows = []
    for imgs, context in groups + [([p for p, _ in stress], None)]:
        contexts = [context] * len(imgs) if context else [d for _, d in stress]
        for r, ctx in zip(predict_and_match(model, imgs, conf=conf, nms_iou=nms_iou, imgsz=imgsz), contexts):
            out_name = f"{len(rows) + 1:02d}_{r.image.stem}.jpg"
            cv2.imwrite(str(out_dir / out_name), draw_result(r, names))
            s = summarize([r])
            rows.append({"file": out_name, "source": ctx, "faces": s["faces"], "correct": s["correct"],
                         "missed": s["missed"], "wrong_identity": s["wrong_identity"],
                         "false_positive": s["false_positive"], "caption": caption_for(r, names, ctx)})
    df = pd.DataFrame(rows)
    lines = ["# Milestone 3 detection gallery", "",
             f"Fine-tuned YOLOv8n, confidence >= {conf}, NMS IoU {nms_iou}. Grades: **Success** = at least 8 of 9 faces "
             "correctly identified, **Partial** = at least half, **Failure** = fewer. Box colours: "
             "**green** = correct identity, **red** = face found but wrong identity (true identity in brackets), "
             "**orange** = false positive, **dashed magenta** = missed face.", "",
             "Stress-test images are harder, exactly-relabelled variants of test frames "
             "(smaller faces, low light, blur, crowding); they are included to show failure modes "
             "and are not part of the reported test metrics.", ""]
    for row in rows:
        lines += [f"### {row['file']}", "", f"![{row['file']}]({row['file']})", "", row["caption"], ""]
    (out_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")
    df.to_csv(out_dir / "gallery_index.csv", index=False)
    return df


# --------------------------------------------------------------------------- #
# Bookkeeping
# --------------------------------------------------------------------------- #
def save_run_logs(run_dir: Path, dest: Path) -> None:
    """Copy the small, reviewable training artefacts (not the checkpoints) into results/."""
    dest.mkdir(parents=True, exist_ok=True)
    for name in ("results.csv", "args.yaml", "results.png", "confusion_matrix.png", "PR_curve.png",
                 "F1_curve.png", "labels.jpg"):
        if (run_dir / name).is_file():
            shutil.copy2(run_dir / name, dest / name)


def fmt(x, digits: int = 3) -> str:
    """Numbers for tables: NaN -> n/a, whole numbers without decimals, tiny values (e.g. lr0) unrounded."""
    try:
        if x != x:  # NaN
            return "n/a"
        if float(x).is_integer():
            return str(int(x))
        if 0 < abs(x) < 0.01:
            return f"{x:g}"
        return f"{x:.{digits}f}"
    except (TypeError, ValueError):
        return str(x)


def md_table(df, digits: int = 3) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(fmt(row[c], digits) if isinstance(row[c], float) else str(row[c])
                                       for c in cols) + " |")
    return "\n".join(lines)
